parent=base
import=common/keycloak

locales=en,ro
styles=css/styles.css
scripts=js/theme.js

# Custom properties
logoUrl=img/Termograf.svg
logoAlt=Termograf
favIconUrl=img/Favicon.ico

# Custom UI elements
customHeader=Header with Termograf branding
customFooter=Footer with Termograf branding