parent=keycloak.v2
import=common/keycloak
locales=en,ro
styles=css/styles.css
scripts=js/theme.js

# Theme metadata
name=termograf
version=1.0

# Branding
masterRealmName=Termograf Administration
logoDark=img/Termograf_logo.svg
logoLight=img/Termograf_logo.svg
favicon=img/favicon.ico

# UI Customization
resourcesPath=resources
loginLogoUrl=/auth/resources/termograf/admin/img/Termograf_logo.svg